spring.application.name=account-service

server.port=${PORT:8081}

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_account}
spring.mongodb.database=ridelink_account

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
