spring.application.name=fare-payment-service
server.port=8083

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://AD:kaveesha@cluster1.ztnc2xm.mongodb.net/ridelink_fare_payment_db?retryWrites=true&w=majority
