spring.application.name=fare-payment-service
server.port=${PORT:8084}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_fare_payment_db}
spring.data.mongodb.auto-index-creation=true
security.jwt-secret=${JWT_SECRET}
security.internal-token=${FARE_SERVICE_TOKEN:}
payment.ride-url=${RIDE_SERVICE_URL:http://localhost:8083}
payment.ride-token=${RIDE_INTERNAL_TOKEN:}
payment.connect-timeout-ms=${SERVICE_CONNECT_TIMEOUT_MS:2000}
payment.read-timeout-ms=${SERVICE_READ_TIMEOUT_MS:5000}
spring.jackson.deserialization.fail-on-unknown-properties=true
