spring.application.name=driver-vehicle-service
server.port=${PORT:8082}
spring.datasource.url=${DRIVER_DB_URL:jdbc:mysql://localhost:3306/ridelink_driver_vehicle_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DRIVER_DB_USERNAME:root}
spring.datasource.password=${DRIVER_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
security.jwt-secret=${JWT_SECRET}
security.internal-token=${DRIVER_SERVICE_TOKEN:}
spring.jackson.deserialization.fail-on-unknown-properties=true
