spring.application.name=driver-vehicle-service
server.port=8082

spring.data.mongodb.uri=mongodb://ridelink_user:${MONGODB_PASSWORD}@ac-f9izoem-shard-00-00.yxuzgkw.mongodb.net:27017,ac-f9izoem-shard-00-01.yxuzgkw.mongodb.net:27017,ac-f9izoem-shard-00-02.yxuzgkw.mongodb.net:27017/?ssl=true&replicaSet=atlas-xibv1k-shard-0&authSource=admin&appName=RideLinkCluster
spring.data.mongodb.database=ridelink_driver_vehicle_db
spring.data.mongodb.auto-index-creation=true
